# Generated by Django 3.0.5 on 2020-05-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(upload_to='images/type', verbose_name='商品类型图片'),
        ),
    ]
