# Generated by Django 3.0.5 on 2020-05-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200503_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(upload_to='images/goods', verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='image',
            field=models.ImageField(upload_to='images/goods', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='indexgoodsbanner',
            name='image',
            field=models.ImageField(upload_to='images/banner', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='indexpromotionbanner',
            name='image',
            field=models.ImageField(upload_to='images/banner', verbose_name='活动图片'),
        ),
    ]
