# Generated by Django 3.0.5 on 2020-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200504_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexgoodsbanner',
            name='url',
            field=models.CharField(default='#', max_length=256, verbose_name='商品链接'),
        ),
    ]
