# Generated by Django 3.0.5 on 2020-05-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200504_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='index',
            field=models.SmallIntegerField(default=0, verbose_name='展示顺序'),
        ),
    ]
